import Footer from "@/components/shared/Footer/Footer";
import Navbar from "@/components/shared/Navbar/Navbar";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";

const inter = Inter({
	variable: "--inter-font",
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const poppins = Poppins({
	variable: "--poppins-font",
	subsets: ["latin"],
	weight: ["100", "200", "300", "500", "600", "800"],
});

export const metadata = {
	title: "BookLend - Online Book Borrowing Platform",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			data-theme="light"
			className={`${inter.className} h-full antialiased`}
		>
			<body className="min-h-full flex flex-col">
				<Navbar></Navbar>
				<main>{children}</main>
				<Footer></Footer>
			</body>
		</html>
	);
}
